#!/bin/bash

# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias cp='cp -iv'                           # Preferred 'cp' implementation
alias mv='mv -iv'                           # Preferred 'mv' implementation
alias mkdir='mkdir -pv'                     # Preferred 'mkdir' implementation
alias ll='ls -FGlAhp | ccze -A -o nolookups'                       # Preferred 'ls' implementation

alias cd..='cd ../'                         # Go back 1 directory level (for fast typers)
alias ..='cd ../../'                           # Go back 2 directory level
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'

alias finder='open -a Finder ./'                 # f:            Opens current directory in MacOS Finder
alias ~="cd ~"                              # ~:            Go Home
alias c='clear'                             # c:            Clear terminal display

tail () { /usr/bin/tail -f $@ | ccze -A -o nolookups; }

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -oG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# git aliases
alias gsall="find . -maxdepth 1 -mindepth 1 -type d -exec sh -c '(echo {} && cd {} && git status -s && echo)' \;"

alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# Reservix
alias portal='cd $PORTAL_DIR'
alias core='cd $CORE_DIR'
alias mitm="cd ~/vhosts/docker-portal && make mitm"
alias rxup="export CORE_HTTP_PORT= && export CORE_HTTPS_PORT= && cd ~/vhosts/docker-portal && export PORTAL_XDEBUG_ENABLE=off && make up && portal"
alias rxupx="export CORE_HTTP_PORT= && export CORE_HTTPS_PORT= && cd ~/vhosts/docker-portal && export PORTAL_XDEBUG_ENABLE=on  && make up && portal"
alias rxdown="cd ~/vhosts/docker-portal && make down && cd ~/vhosts/core/docker && make down && portal"
alias coreup="rxdown && export CORE_XDEBUG_ENABLE=false && export CORE_HTTP_PORT=1988 && export CORE_HTTPS_PORT=1989 && cd ~/vhosts/core/docker && make up && cd ~/vhosts/docker-portal && export PORTAL_XDEBUG_ENABLE=off && make up && portal"
alias coreupx="rxdown && export CORE_XDEBUG_ENABLE=true && export CORE_HTTP_PORT=1988 && export CORE_HTTPS_PORT=1989 && cd ~/vhosts/core/docker && make up && rxupx"
alias ec2Instances="aws ec2 describe-instances --filters Name=tag-key,Values=aws:autoscaling:groupName --query 'Reservations[*].Instances[*].{InstanceID:InstanceId,Name:Tags[?Key==\`aws:autoscaling:groupName\`]|[0].Value}' --output table --profile"


# networking
alias ip="wget -qO- https://diagnostic.opendns.com/myip | pbcopy | printf '=> Public IP address copied to pasteboard.\n'"
alias localip="ipconfig getifaddr en1 | pbcopy | printf '=> Local IP address copied to pasteboard.\n'"
alias ping="prettyping --nolegend"

# other tools
alias top="htop"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_ed25519.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
alias flushdns="sudo killall -HUP mDNSResponder"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
