#!/bin/bash

run_help() {

cat <<EOT
OS X dotfiles - Sebastian Kenk - http://sebastiankenk.de/

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    -l, --list      Print a list of additional software to install
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/sbknk/dotfiles/

Copyright (c) Sebastian Kenk
Licensed under the MIT license.
EOT

}
